Updated pre-merge

diff --git a/.github/workflows/pre-merge.yml b/.github/workflows/pre-merge.yml
--- a/.github/workflows/pre-merge.yml
+++ b/.github/workflows/pre-merge.yml
@@ -9,11 +9,9 @@ on:
     branches:
       - main
       - release-*
-  workflow_dispatch:
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+env:
+  MARKDOWNLINT_CLI_VER: 0.44.0
 
 jobs:
   pre-checks:
@@ -21,45 +19,32 @@ jobs:
     outputs:
       filtered_projects: ${{ steps.filter-changes.outputs.filtered_projects }}
       other_changed_projects: ${{ steps.filter-changes.outputs.other_changed_projects }}
-      artifact_path: ${{ steps.arti-path.outputs.artifact_path }}
+    env:
+      GITHUB_ACTIONS: true
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - name: "Verify Branch Name"
-        uses: open-edge-platform/orch-ci/verify-branch-name@main
+        uses: open-edge-platform/orch-ci/verify-branch-name@0.1.5
       - name: "Discover Changed Subfolders"
         id: discover-changes
-        uses: open-edge-platform/orch-ci/discover-changed-subfolders@main
+        uses: open-edge-platform/orch-ci/discover-changed-subfolders@0.1.5
       - name: "Filter Out Unwanted Changed Subfolders"
         id: filter-changes
         run: |
-          folders_to_remove='[".github",".reuse","LICENSES",".git","tools",""]'
+          folders_to_remove='[".github",".reuse","LICENSES",""]'
+
           changed_projects='${{ steps.discover-changes.outputs.changed_projects }}'
           filtered_projects=$(echo "$changed_projects" | jq -cr --argjson folders_to_remove "$folders_to_remove" 'map(select(. as $item | $folders_to_remove | index($item) | not))')
           other_changed_projects=$(echo "$changed_projects" | jq -cr --argjson filtered_projects "$filtered_projects" 'map(select(. as $item | $filtered_projects | index($item) | not))')
+
           echo "filtered_projects=$filtered_projects" >> $GITHUB_OUTPUT
           echo "other_changed_projects=$other_changed_projects" >> $GITHUB_OUTPUT
-          echo "filtered_projects=$filtered_projects" >> $GITHUB_ENV
-      - name: "Artifact Folder or Files"
-        id: arti-path
-        run: |
-          if [ "$filtered_projects" == '["standalone-node"]' ]; then
-            echo "artifact_path<<EOF" >> $GITHUB_OUTPUT
-            echo "standalone-node/out/" >> $GITHUB_OUTPUT
-            echo "EOF" >> $GITHUB_OUTPUT
-          else
-            echo "artifact_path=empty" >> $GITHUB_OUTPUT
-          fi
-      - name: Clean up preinstalled tools
-        run: |
-          sudo rm -rf /usr/local/lib/android
-          sudo rm -rf /opt/hostedtoolcache
-          sudo rm -rf /usr/share/dotnet
   pre-merge-root:
     needs: pre-checks
-    if: ${{ contains(needs.pre-checks.outputs.other_changed_projects, '.github') || contains(needs.pre-checks.outputs.other_changed_projects, '.reuse') || contains(needs.pre-checks.outputs.other_changed_projects, 'LICENSES') || contains(needs.pre-checks.outputs.other_changed_projects, '""' ) || contains(needs.pre-checks.outputs.other_changed_projects, 'tools')}}
+    if: ${{ contains(needs.pre-checks.outputs.other_changed_projects, '.github') || contains(needs.pre-checks.outputs.other_changed_projects, '.reuse') || contains(needs.pre-checks.outputs.other_changed_projects, 'LICENSES') || contains(needs.pre-checks.outputs.other_changed_projects, '""')}}
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
         with:
           node-version: '18'
@@ -87,46 +72,47 @@ jobs:
       fail-fast: false
       matrix:
         project_folder: ${{ fromJson(needs.pre-checks.outputs.filtered_projects) }}
-    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@main
+    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@0.1.5
     with:
       run_security_scans: false
       run_version_check: true
       run_dep_version_check: true
       run_build: true
       run_lint: true
-      run_test: false #only for testing 
+      run_test: true
       run_validate_clean_folder: true
       run_docker_build: true
-      run_artifact: true
-      artifacts_path: ${{ needs.pre-checks.outputs.artifact_path }}
+      run_scan_containers: false
+      run_artifact: false
       prefix_tag_separator: "/"
       project_folder: ${{ matrix.project_folder }}
-      trivy_config_path: '${{ matrix.project_folder }}/trivy.yaml'
+      trivy_image_skip:  "postgres:16.4"
+      trivy_config_path: ${{ matrix.project_folder }}/trivy.yaml
     secrets: inherit
   final-check:
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    needs: [pre-merge-root, pre-merge-pipeline]
-    steps:
-      - name: Final Status Check
-        run: |
-          pre_merge_root_pipeline="${{ needs.pre-merge-root.result }}"
-          pre_merge_pipeline="${{ needs.pre-merge-pipeline.result }}"
+      runs-on: ubuntu-latest
+      if: ${{ always() }}
+      needs: [pre-merge-root, pre-merge-pipeline]
+      steps:
+        - name: Final Status Check
+          run: |
+            pre_merge_root_pipeline="${{ needs.pre-merge-root.result }}"
+            pre_merge_pipeline="${{ needs.pre-merge-pipeline.result }}"
 
-          results=("pre_merge_root_pipeline" "pre_merge_pipeline")
-          status="OK"
-          
-          for result in "${results[@]}"; do
-            pipeline_result=$(eval echo \$$result)
-            echo "${result} result: $pipeline_result"
-            if [[ "$pipeline_result" != "success" && "$pipeline_result" != "skipped" ]]; then
-              status="KO"
+            results=("pre_merge_root_pipeline" "pre_merge_pipeline")
+            status="OK"
+            
+            for result in "${results[@]}"; do
+              pipeline_result=$(eval echo \$$result)
+              echo "${result} result: $pipeline_result"
+                if [[ "$pipeline_result" != "success" && "$pipeline_result" != "skipped" ]]; then
+                status="KO"
+              fi
+            done
+            
+            if [[ "$status" == "OK" ]]; then
+              echo "Pre-merge check passed successfully."
+            else
+              echo "All pre-merge checks failed or were skipped. PR can't get merged"
+              exit 1
             fi
-          done
-          
-          if [[ "$status" == "OK" ]]; then
-            echo "Pre-merge check passed successfully."
-          else
-            echo "All pre-merge checks failed or were skipped. PR can't get merged"
-            exit 1
-          fi
